/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Whisu
 */
public class PESEL extends javax.swing.JFrame {

    public int licznik = 0;
    String[] pesle = new String[100];
    

    /**
     * Creates new form PESEL
     */
    public PESEL() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pesel = new javax.swing.JTextField();
        Sprawdz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PESEL");
        setPreferredSize(new java.awt.Dimension(450, 150));

        jLabel1.setText("Wpisz tutaj PESEL który chcesz zweryfikować:");

        Sprawdz.setText("Sprawdz!");
        Sprawdz.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SprawdzMouseClicked(evt);
            }
        });
        Sprawdz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SprawdzActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pesel, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sprawdz)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pesel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sprawdz)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SprawdzMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SprawdzMouseClicked
        ZapisDoPliku zap = new ZapisDoPliku();
        String psl = pesel.getText();
        String poprawnosc = "";

        int[] skl = new int[11];

        for (int i = 0; i != 11; i++) {
            skl[i] = Integer.parseInt(psl.substring(i, i + 1));
        }
        //1×a + 3×b + 7×c + 9×d + 1×e + 3×f + 7×g + 9×h + 1×i + 3×j
        int suma = (1 * skl[0]) + (3 * skl[1]) + (7 * skl[2]) + (9 * skl[3]) + (1 * skl[4]) + (3 * skl[5]) + (7 * skl[6]) + (9 * skl[7]) + (1 * skl[8]) + (3 * skl[9]);
        suma = suma % 10;
        if (suma == 0 && suma == skl[10]) {
            poprawnosc = "Poprawny PESEL!";
            pesle[licznik] = psl;
            licznik++;
        } else {
            suma = 10 - suma;
        }
        if (suma == skl[10]) {
            poprawnosc = "Poprawny PESEL!";
            pesle[licznik] = psl;
            licznik++;

        } else {
            poprawnosc = "Niepoprawny PESEL!";
        }

        String komunikat = "Poprawsnosc: " + poprawnosc;
        JOptionPane.showMessageDialog(this, komunikat);
        try {
            zap.zapisDoPliku(pesle);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(PESEL.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SprawdzMouseClicked

    private void SprawdzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SprawdzActionPerformed

    }//GEN-LAST:event_SprawdzActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PESEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PESEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PESEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PESEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PESEL().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sprawdz;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField pesel;
    // End of variables declaration//GEN-END:variables

}
